name: Dive Goals
description: Diving logbook
markdown: kramdown 
exclude: ["scss", "Gemfile","Gemfile.lock", "README.md"]
disqus_short_name: "Ryan McKnight"
url: "https://www.divegoals.com"
baseurl: ""
